apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: helms.helmcontroller.k8s.io
spec:
  group: helmcontroller.k8s.io
  version: v1alpha1
  names:
    kind: Helm
    plural: helms
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        spec:
          type: object
          required:
            - imageName
          properties:
            replicas:
              type: integer
              minimum: 1
            imageName:
              type: string
