{{- if .Values.serviceAccount.create -}}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "controller.fullname" . }}
  labels:
{{ include "controller.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "controller.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: ""
{{- end -}}