apiVersion: v1
kind: ConfigMap
metadata:
  name: dns-script
  labels:
    {{- include "cluster-config.labels" . | nindent 4 }}
data:
  dns.sh: |
    !#/bin/bash

    # Prepull big images
    {{- range .Values.prePullImages -}}
    docker pull {{ . }}
    {{- end -}}

    # Add hello service
    echo "
    service stuff
    " > /etc/system/...

    # Enable hello service with dbus
    /var/run/dbus/system_bus_socket

    # dbus start hello service
