apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "cluster-config.fullname" . }}
  labels:
    {{- include "cluster-config.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "cluster-config.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cluster-config.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          command:
            - bash
            - /var/run/custom_config/dns.sh
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: docker-sock
            mountPath: /var/run/docker.sock
          - name: dbus-sock
            mountPath: /var/run/dbus/system_bus_socket
          - name: scripts
            mountPath: /var/run/custom_config
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
        - name: dbus-sock
          hostPath:
            path: /var/run/dbus/system_bus_socket
        - name: scripts
          configMap:
            name: dns-script
