image:
  repository: debian
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

securityContext:
  privileged: true
  runAsUser: 0

resources: {}

tolerations:
  - key: node-role.kubernetes.io/master
    effect: NoSchedule
